"""Authetication

Revision ID: 127c2c396c5
Revises: 2eafdc374d08
Create Date: 2016-04-04 23:38:25.667328

"""

# revision identifiers, used by Alembic.
revision = '127c2c396c5'
down_revision = '2eafdc374d08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
